name: Dotnet 7 Web API Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test
  build-push:
    name: Build/Push
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup commit sha
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Build non-master
        run: docker build --tag Files:${{ steps.short-sha.outputs.sha }} .

      - name: Build master
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        uses: jwalton/gh-ecr-push@v1
        env:
          REGISTRY: 232187837350.dkr.ecr.us-east-1.amazonaws.com/softiadata
          IMAGE: files
          SHA: ${{ steps.short-sha.outputs.sha }}
          REF: ${{ github.ref }}
          ISMASTER: ${{ github.ref == 'master' }}
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: ${{env.IMAGE}}:${{ env.SHA }}